// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	win fyne.Window

	mayText     *widget.Entry
	mustText    *widget.Entry
	trashButton *widget.Button
	theBox      *fyne.Container
}

func newGUI() *gui {
	return &gui{}
}

func (g *gui) makeUI() fyne.CanvasObject {
	g.mayText = &widget.Entry{Text: "", PlaceHolder: "May", MultiLine: false, Password: false}
	g.mustText = &widget.Entry{Text: "", PlaceHolder: "Must", MultiLine: false, Password: false}
	g.trashButton = &widget.Button{Text: "Trash!", Importance: 1, Icon: theme.DeleteIcon(), Alignment: 0, OnTapped: g.trashTap}
	g.theBox = container.NewVBox(
		&widget.Label{Text: "Welcome to Lexitrash!", TextStyle: fyne.TextStyle{Bold: true, Italic: false, Monospace: true, Symbol: false, TabWidth: 0, Underline: false}, Alignment: 1, Wrapping: 0},
		g.mustText,
		g.mayText,
		g.trashButton)

	return container.NewCenter(
		g.theBox)
}

func (g *gui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("main.gui.go")
	g.win = w
	w.Resize(fyne.NewSize(365, 308))
	w.SetContent(g.makeUI())
	return w
}